name: Docker Image CI

on:
  workflow_dispatch:  # Ce workflow ne s'exécutera que manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
